#!/usr/bin/env python3
"""tools/der_to_c.py — embed a DER file (X.509 cert, etc.) as a C byte array.

Used to bake trusted CA certs directly into the NT4 client (no filesystem
cert store, no PEM_PARSE_C needed — mbedtls_x509_crt_parse takes DER directly).

    python3 tools/der_to_c.py cert.der SYMBOL_NAME > net/embedded_cert.h
"""
import sys

def main():
    if len(sys.argv) != 3:
        print("usage: der_to_c.py <file.der> <c_symbol_name>", file=sys.stderr)
        return 1
    path, name = sys.argv[1], sys.argv[2]
    with open(path, "rb") as f:
        data = f.read()

    print(f"/* Generated by tools/der_to_c.py from {path} ({len(data)} bytes). */")
    print(f"static const unsigned char {name}[] = {{")
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        print("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    print("};")
    print(f"static const unsigned int {name}_len = {len(data)};")
    return 0

if __name__ == "__main__":
    sys.exit(main())
