#!/usr/bin/env python3
"""Turn a captured instagrapi feed/timeline/ request (headers + body) into a
C header the NT4 client bakes in as static templates. Excludes headers that
core/http.c already synthesizes (Host, Content-Length) and headers that get
freshly regenerated client-side each request (timestamps, random telemetry,
X-Pigeon-Session-Id) -- those are listed separately as "dynamic" so the C
code knows what NOT to expect baked.

Output is written straight to vm/ig_session_private.h in the instagram-on-nt40
repo -- vm/ is already gitignored (same place the TLS mock's private key
lives), and this file contains a REAL live Instagram session. Never commit it.
"""
import json
import re

SCRATCH = "/private/tmp/claude-502/-Users-zobithecat-Documents-projects-etc-projects-instagram-on-nt40/a89f1ba5-bf7d-4c71-9790-731c82e66169/scratchpad"
OUT = "/Users/zobithecat/Documents/projects/etc_projects/instagram-on-nt40/vm/ig_session_private.h"

DYNAMIC_HEADERS = {
    "x-pigeon-session-id", "x-pigeon-rawclienttime",
    "x-ig-bandwidth-speed-kbps", "x-ig-bandwidth-totalbytes-b", "x-ig-bandwidth-totaltime-ms",
    "x-ig-salt-ids", "x-cm-latency",
}
SKIP_HEADERS = {"host", "content-length"}  # core/http.c synthesizes these itself
DYNAMIC_BODY_FIELDS = {
    "app_start_time", "client_recorded_request_time_ms", "request_build_time", "will_sound_on",
}


def c_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    req = json.load(open(f"{SCRATCH}/captured_request.json"))
    headers = req["headers"]
    body = json.loads(req["body"])

    static_headers = [(k, v) for k, v in headers.items()
                      if k.lower() not in DYNAMIC_HEADERS and k.lower() not in SKIP_HEADERS]
    static_body = {k: v for k, v in body.items() if k not in DYNAMIC_BODY_FIELDS}

    lines = []
    lines.append("/* vm/ig_session_private.h -- GENERATED by export_ig_session.py.")
    lines.append(" * Contains a REAL live Instagram private-API session. DO NOT COMMIT.")
    lines.append(" * (vm/ is already gitignored in this repo.) Regenerate by re-running the")
    lines.append(" * export script against a fresh instagrapi capture if the underlying")
    lines.append(" * Instagram session itself is ever renewed (new login). */")
    lines.append("#ifndef IG_SESSION_PRIVATE_H")
    lines.append("#define IG_SESSION_PRIVATE_H")
    lines.append("")
    lines.append('#define IG_PRIVATE_HOST "i.instagram.com"')
    lines.append("#define IG_PRIVATE_PORT 443")
    path = re.sub(r"^https://[^/]+", "", req["url"])
    lines.append(f'#define IG_PRIVATE_PATH "{path}"')
    lines.append("")
    lines.append("typedef struct { const char *name, *value; } IgStaticHeader;")
    lines.append("")
    lines.append(f"#define IG_STATIC_HEADERS_COUNT {len(static_headers)}")
    lines.append("static const IgStaticHeader IG_STATIC_HEADERS[IG_STATIC_HEADERS_COUNT] = {")
    for k, v in static_headers:
        lines.append(f'    {{ "{c_escape(k)}", "{c_escape(v)}" }},')
    lines.append("};")
    lines.append("")
    lines.append("/* Static body fields (verbatim from a real captured request). The C")
    lines.append(" * body builder combines these with 4 freshly computed values each run:")
    lines.append(" * app_start_time / client_recorded_request_time_ms / request_build_time")
    lines.append(" * (all = current time in ms) and will_sound_on (fresh random 0/1). */")
    for k, v in static_body.items():
        name = f"IG_BODY_{k.upper()}"
        if isinstance(v, str):
            lines.append(f'#define {name} "{c_escape(v)}"')
        elif isinstance(v, bool):
            lines.append(f"#define {name} {1 if v else 0}")
        else:
            lines.append(f"#define {name} {v}")
    lines.append("")
    lines.append("#endif /* IG_SESSION_PRIVATE_H */")

    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT}")
    print(f"  static headers: {len(static_headers)}")
    print(f"  static body fields: {len(static_body)}")
    print(f"  dynamic (client-regenerated) headers: {sorted(DYNAMIC_HEADERS)}")
    print(f"  dynamic (client-regenerated) body fields: {sorted(DYNAMIC_BODY_FIELDS)}")


if __name__ == "__main__":
    main()
